export const instruments = {
  gayageum:{name:'가야금',desc:'현을 클릭하거나 키보드 A–K로 연주할 수 있습니다.',type:'string',notes:['C4','D4','E4','G4','A4','C5','D5','E5']},
  haegeum:{name:'해금',desc:'지속음 중심의 해금 음색을 연주합니다.',type:'bowed',notes:['G3','A3','C4','D4','E4','G4','A4','C5']},
  daegeum:{name:'대금',desc:'숨결이 섞인 관악 음색을 연주합니다.',type:'wind',notes:['D4','E4','G4','A4','C5','D5','E5','G5']},
  janggu:{name:'장구',desc:'채편과 북편의 기본 타격을 연주합니다.',type:'percussion',notes:['deong','deok','kung','dda']},
  buk:{name:'북',desc:'서로 다른 세기의 북 타격을 연주합니다.',type:'percussion',notes:['soft','mid','hard','rim']},
  danso:{name:'단소',desc:'맑은 관악 음색으로 기본 음계를 연주합니다.',type:'wind',notes:['G4','A4','C5','D5','E5','G5','A5','C6']}
};
const midi=n=>{const m=/^([A-G])(#?)(-?\d)$/.exec(n);if(!m)return 60;const pc={C:0,D:2,E:4,F:5,G:7,A:9,B:11}[m[1]]+(m[2]?1:0);return(Number(m[3])+1)*12+pc};
const freq=n=>440*Math.pow(2,(midi(n)-69)/12);
export class AudioEngine{
  constructor(){this.ctx=null;this.active=[];this.sampleCache=new Map();}
  ensure(){if(!this.ctx)this.ctx=new(window.AudioContext||window.webkitAudioContext)();if(this.ctx.state==='suspended')this.ctx.resume();return this.ctx;}
  async loadSample(url){if(this.sampleCache.has(url))return this.sampleCache.get(url);const r=await fetch(url);if(!r.ok)throw new Error('sample not found');const b=await r.arrayBuffer();const a=await this.ensure().decodeAudioData(b);this.sampleCache.set(url,a);return a}
  stopAll(){for(const n of this.active){try{n.stop()}catch{}}this.active=[]}
  play(inst,note,velocity=90,duration=.7,when=0,ctx=null){ctx=ctx||this.ensure();const t=(ctx.currentTime||0)+when;const gain=ctx.createGain();gain.connect(ctx.destination);const v=Math.max(.05,Math.min(1,velocity/127));if(inst==='janggu'||inst==='buk')return this.percussion(ctx,gain,inst,note,v,t);const f=freq(note);const osc=ctx.createOscillator();const osc2=ctx.createOscillator();const filt=ctx.createBiquadFilter();const noise=ctx.createBufferSource();const ng=ctx.createGain();const buf=ctx.createBuffer(1,Math.max(1,Math.floor(ctx.sampleRate*duration)),ctx.sampleRate);const d=buf.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1);noise.buffer=buf;
    if(inst==='gayageum'){osc.type='triangle';osc2.type='sine';osc.frequency.value=f;osc2.frequency.value=f*2.01;filt.type='lowpass';filt.frequency.value=2800;gain.gain.setValueAtTime(.001,t);gain.gain.exponentialRampToValueAtTime(.65*v,t+.01);gain.gain.exponentialRampToValueAtTime(.001,t+duration);ng.gain.value=.02*v}
    else if(inst==='haegeum'){osc.type='sawtooth';osc2.type='triangle';osc.frequency.value=f;osc2.frequency.value=f*1.002;filt.type='bandpass';filt.frequency.value=f*2;filt.Q.value=.7;gain.gain.setValueAtTime(.001,t);gain.gain.exponentialRampToValueAtTime(.28*v,t+.08);gain.gain.setValueAtTime(.25*v,t+Math.max(.1,duration-.1));gain.gain.exponentialRampToValueAtTime(.001,t+duration);ng.gain.value=.008*v}
    else{osc.type='sine';osc2.type='triangle';osc.frequency.value=f;osc2.frequency.value=f*2;filt.type='lowpass';filt.frequency.value=3400;gain.gain.setValueAtTime(.001,t);gain.gain.exponentialRampToValueAtTime(.35*v,t+.06);gain.gain.exponentialRampToValueAtTime(.001,t+duration);ng.gain.value=.055*v}
    osc.connect(filt);osc2.connect(filt);noise.connect(ng);ng.connect(filt);filt.connect(gain);osc.start(t);osc2.start(t);noise.start(t);osc.stop(t+duration+.03);osc2.stop(t+duration+.03);noise.stop(t+duration+.03);this.active.push(osc,osc2,noise);return[osc,osc2,noise]
  }
  percussion(ctx,gain,inst,note,v,t){const osc=ctx.createOscillator();const noise=ctx.createBufferSource();const ng=ctx.createGain();const filt=ctx.createBiquadFilter();const len=.28;const buf=ctx.createBuffer(1,Math.floor(ctx.sampleRate*len),ctx.sampleRate);const d=buf.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);noise.buffer=buf;osc.type='sine';const map=inst==='janggu'?{deong:150,deok:240,kung:95,dda:330}:{soft:85,mid:100,hard:115,rim:250};osc.frequency.value=map[note]||120;filt.type='bandpass';filt.frequency.value=(note==='deok'||note==='dda'||note==='rim')?1800:550;filt.Q.value=.7;gain.gain.setValueAtTime(.8*v,t);gain.gain.exponentialRampToValueAtTime(.001,t+len);ng.gain.value=.4*v;osc.connect(gain);noise.connect(ng);ng.connect(filt);filt.connect(gain);osc.start(t);noise.start(t);osc.stop(t+len);noise.stop(t+len);this.active.push(osc,noise);return[osc,noise]}
}
export async function renderEventsToWav(events,duration){const sr=44100;const ctx=new OfflineAudioContext(2,Math.ceil((duration+.6)*sr),sr);const engine=new AudioEngine();for(const e of events)engine.play(e.instrument,e.note,e.velocity||90,e.duration||.5,e.time||0,ctx);const rendered=await ctx.startRendering();return audioBufferToWav(rendered)}
function audioBufferToWav(buffer){const nc=buffer.numberOfChannels,len=buffer.length*nc*2+44,ab=new ArrayBuffer(len),v=new DataView(ab);let p=0;const s=x=>{for(let i=0;i<x.length;i++)v.setUint8(p++,x.charCodeAt(i))};s('RIFF');v.setUint32(p,36+buffer.length*nc*2,true);p+=4;s('WAVEfmt ');v.setUint32(p,16,true);p+=4;v.setUint16(p,1,true);p+=2;v.setUint16(p,nc,true);p+=2;v.setUint32(p,buffer.sampleRate,true);p+=4;v.setUint32(p,buffer.sampleRate*nc*2,true);p+=4;v.setUint16(p,nc*2,true);p+=2;v.setUint16(p,16,true);p+=2;s('data');v.setUint32(p,buffer.length*nc*2,true);p+=4;const chans=[];for(let c=0;c<nc;c++)chans.push(buffer.getChannelData(c));for(let i=0;i<buffer.length;i++)for(let c=0;c<nc;c++){let x=Math.max(-1,Math.min(1,chans[c][i]));v.setInt16(p,x<0?x*32768:x*32767,true);p+=2}return new Blob([ab],{type:'audio/wav'})}